service: AuthorizationService

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - '!**/*'

functions:
  basicAuthorizer:
    package:
      include:
        - dist/BasicAuthorizer/*
    handler: dist/BasicAuthorizer/index.handler
    events:
      - http:
          path: /my-endpoint
          method: any
          authorizer:
            name: basicAuthorizer
            arn: arn:aws:lambda:us-east-1:123456789012:function:my-service-basicAuthorizer
