service: ImportService

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: "s3:*"
      Resource: arn:aws:s3:::${self:custom.s3BucketName}/*
    - Effect: Allow
      Action: "sqs:*"
      Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${self:custom.sqsQueueName}




  environment:
    REGION: ${self:provider.region}
    BUCKET_NAME: ${self:custom.s3BucketName}
    UPLOAD_PATH: ${self:custom.uploadPath}
    SQS_QUEUE_NAME: ${self:custom.sqsQueueName}


custom:
  s3BucketName: "avshoplearntask-uploadbucket"
  uploadPath: "uploaded"
  sqsQueueName: "catalogItemsQueue"

package:
  individually: true
  patterns:
    - '!**/*'

functions:
  importProductsFile:
    package:
      include:
       - dist/ImportProductsFile/*
    handler: dist/ImportProductsFile/index.handler
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true


  importFileParser:
    package:
      include:
        - dist/ImportFileParser/*
    handler: dist/ImportFileParser/index.handler
    events:
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.uploadPath}
          existing: true

